<?php ?>
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="meeja.net"/>
<title>Is it Beer o'Clock?</title>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800" rel="stylesheet" type="text/css" />
<link href='https://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href="/assets/css/style.css" />
<link rel="stylesheet" type="text/css" href="http://assets.zensoft.net/external/bootstrap/css/bootstrap.min.css" />
<script src="http://assets.zensoft.net/external/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

<!-- container --><div class="container">

